package cn.cyansoft.makeappo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppoDoctor<M extends BaseAppoDoctor<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDeptId(java.lang.Integer deptId) {
		set("deptId", deptId);
	}

	public java.lang.Integer getDeptId() {
		return get("deptId");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setEducation(java.lang.String education) {
		set("education", education);
	}

	public java.lang.String getEducation() {
		return get("education");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setStartTime(java.lang.String startTime) {
		set("startTime", startTime);
	}

	public java.lang.String getStartTime() {
		return get("startTime");
	}
	public void setStopTime(java.lang.String stopTime) {
		set("stopTime", stopTime);
	}
	
	public java.lang.String getStopTime() {
		return get("stopTime");
	}

	public void setAbleAppoNum(java.lang.Integer ableAppoNum) {
		set("ableAppoNum", ableAppoNum);
	}

	public java.lang.Integer getAbleAppoNum() {
		return get("ableAppoNum");
	}
	
	public void setMoney(java.lang.Integer money) {
		set("money", money);
	}

	public java.lang.Integer getMoney() {
		return get("money");
	}

}
