package cn.cyansoft.makeappo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppoAppointment<M extends BaseAppoAppointment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTime(java.lang.String time) {
		set("time", time);
	}

	public java.lang.String getTime() {
		return get("time");
	}

	public void setDescribe(java.lang.String describe) {
		set("describe", describe);
	}

	public java.lang.String getDescribe() {
		return get("describe");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setDeptId(java.lang.Integer deptId) {
		set("deptId", deptId);
	}

	public java.lang.Integer getDeptId() {
		return get("deptId");
	}

	public void setDocId(java.lang.Integer docId) {
		set("docId", docId);
	}

	public java.lang.Integer getDocId() {
		return get("docId");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}
	
	public void setMoney(java.lang.Integer money) {
		set("money", money);
	}

	public java.lang.Integer getMoney() {
		return get("money");
	}
	
	public void setPayway(java.lang.String payway) {
		set("payway", payway);
	}

	public java.lang.String getPayway() {
		return get("payway");
	}
	
	public void setDiagTime(java.lang.String diagTime) {
		set("diagTime", diagTime);
	}

	public java.lang.String getDiagTime() {
		return get("diagTime");
	}
	
	public void setDiagInfo(java.lang.String diagInfo) {
		set("diagInfo", diagInfo);
	}

	public java.lang.String getDiagInfo() {
		return get("diagInfo");
	}
	

}
