package cn.cyansoft.makeappo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppoSource<M extends BaseAppoSource<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDocId(java.lang.Integer docId) {
		set("docId", docId);
	}

	public java.lang.Integer getDocId() {
		return get("docId");
	}

	public void setTime(java.lang.String time) {
		set("time", time);
	}

	public java.lang.String getTime() {
		return get("time");
	}

	public void setTotal(java.lang.Integer total) {
		set("total", total);
	}

	public java.lang.Integer getTotal() {
		return get("total");
	}

	public void setRemain(java.lang.Integer remain) {
		set("remain", remain);
	}

	public java.lang.Integer getRemain() {
		return get("remain");
	}

}
