package cn.cyansoft.makeappo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppoStop<M extends BaseAppoStop<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDocId(java.lang.Integer docId) {
		set("docId", docId);
	}

	public java.lang.Integer getDocId() {
		return get("docId");
	}

	public void setStopTime(java.lang.String stopTime) {
		set("stopTime", stopTime);
	}

	public java.lang.String getStopTime() {
		return get("stopTime");
	}

	public void setStopDaynum(java.lang.String stopDaynum) {
		set("stopDaynum", stopDaynum);
	}

	public java.lang.String getStopDaynum() {
		return get("stopDaynum");
	}

}
