package cn.cyansoft.makeappo.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("appo_admin", "id", AppoAdmin.class);
		arp.addMapping("appo_appointment", "id", AppoAppointment.class);
		arp.addMapping("appo_dept", "id", AppoDept.class);
		arp.addMapping("appo_doctor", "id", AppoDoctor.class);
		arp.addMapping("appo_registration", "id", AppoRegistration.class);
		arp.addMapping("appo_source", "id", AppoSource.class);
		arp.addMapping("appo_stop", "id", AppoStop.class);
		arp.addMapping("appo_user", "id", AppoUser.class);
	}
}

