package cn.cyansoft.makeappo.model;

import cn.cyansoft.makeappo.model.base.BaseAppoUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppoUser extends BaseAppoUser<AppoUser> {
	public static final AppoUser dao = new AppoUser();
}
