package cn.cyansoft.makeappo.model;

import cn.cyansoft.makeappo.model.base.BaseAppoAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppoAdmin extends BaseAppoAdmin<AppoAdmin> {
	public static final AppoAdmin dao = new AppoAdmin();
}
