package cn.cyansoft.makeappo.model;

import cn.cyansoft.makeappo.model.base.BaseAppoAppointment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppoAppointment extends BaseAppoAppointment<AppoAppointment> {
	public static final AppoAppointment dao = new AppoAppointment();
}
