package cn.cyansoft.makeappo.model;

import cn.cyansoft.makeappo.model.base.BaseAppoDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppoDept extends BaseAppoDept<AppoDept> {
	public static final AppoDept dao = new AppoDept();
}
