package cn.cyansoft.makeappo.model;

import cn.cyansoft.makeappo.model.base.BaseAppoSource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppoSource extends BaseAppoSource<AppoSource> {
	public static final AppoSource dao = new AppoSource();
}
