package cn.cyansoft.makeappo.model;

import cn.cyansoft.makeappo.model.base.BaseAppoRegistration;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppoRegistration extends BaseAppoRegistration<AppoRegistration> {
	public static final AppoRegistration dao = new AppoRegistration();
}
