package cn.cyansoft.makeappo.model;

import cn.cyansoft.makeappo.model.base.BaseAppoDoctor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppoDoctor extends BaseAppoDoctor<AppoDoctor> {
	public static final AppoDoctor dao = new AppoDoctor();
}
