package cn.cyansoft.makeappo.model;

import cn.cyansoft.makeappo.model.base.BaseAppoStop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppoStop extends BaseAppoStop<AppoStop> {
	public static final AppoStop dao = new AppoStop();
}
