package com.bdsht.study01.model;

import com.bdsht.study01.model.base.BaseTBlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TBlog extends BaseTBlog<TBlog> {
	public static final TBlog dao = new TBlog().dao();
}
